paths:
  labelme_input: preprocessing_output
  masks_output: masks_output
  masks_check: masks_check
  dataset_output: datasets/cell_dataset.h5
  model_output: unet_cellcount_model.pth

masks:
  target_label: cell
  preview_sample_rate: 0.2
  preview_seed: 77 # 如果沒有輸入 seed 可以直接取消使用 random seed?

dataset:
  sample_rate_empty: 0.2
  seed: 77
  split: [0.8, 0.1, 0.1]

training:
  batch_size: 16
  epochs: 60
  seed: 77
  learning_rate: 0.0001
  threshold: 0.5
